### ISSUE TITLE
Compiling with gcc 4.6

### ISSUE THREAD

**Issue by GoogleCodeExporter** [BloodRedd/gamekit#144]
```
What steps will reproduce the problem?
1.Try to compile with gcc 4.6
2.Error with ‘ptrdiff_t’ has not been declared
3.Add '#include <cstddef>' to 
'gamekit-read-only/Ogre-1.8/OgreMain/include/OgreOptimisedUtil.h' and compiles

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
Todays's SVN on Fedora Rawhide (FC15/FC16)

Please provide any additional information below.
This is the error:
/gamekit-read-only/Ogre-1.8/OgreMain/include/OgreOptimisedUtil.h:212:49: error: 
‘ptrdiff_t’ has not been declared
/gamekit-read-only/Ogre-1.8/OgreMain/include/OgreOptimisedUtil.h:222:53: error: 
‘ptrdiff_t’ has not been declared
make[2]: *** 
[Ogre-1.8/OgreMain/CMakeFiles/OgreMain.dir/src/OgreEdgeListBuilder.cpp.o] Error 
1
make[1]: *** [Ogre-1.8/OgreMain/CMakeFiles/OgreMain.dir/all] Error 2
make: *** [all] Error 2

```

Original issue reported on code.google.com by `thomasbe...@gmail.com` on 1 Mar 2011 at 5:36

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r856.

We should probably signal/send the patch upstream.


```

Original comment by `xavier.thomas.1980@gmail.com` on 11 Mar 2011 at 3:23
- Changed state: **Fixed**

Attachments:
- [ogre-gcc4.6.diff](https://storage.googleapis.com/google-code-attachments/gamekit/issue-144/comment-1/ogre-gcc4.6.diff)
